export const TECHNIQUES = [
  {
    id: 'pomodoro',
    name: 'Pomodoro',
    duration: 25,
    break: 5,
    sessions: 4,
    description: 'Classic 25-min focus, 5-min break cycle. Best for most tasks.',
    color: '#D4956B',
    bg: '#FDF0E8',
  },
  {
    id: 'short',
    name: 'Short burst',
    duration: 15,
    break: 3,
    sessions: 6,
    description: 'Quick 15-min sprints. Great for warming up or tough subjects.',
    color: '#6B7FD4',
    bg: '#EEF0FB',
  },
  {
    id: 'deep',
    name: 'Deep work',
    duration: 50,
    break: 10,
    sessions: 2,
    description: 'Long 50-min blocks for complex problems that need full immersion.',
    color: '#5DAA88',
    bg: '#EAF3EE',
  },
  {
    id: 'custom',
    name: 'Custom',
    duration: 30,
    break: 5,
    sessions: 4,
    description: 'Set your own focus and break durations.',
    color: '#C47DB8',
    bg: '#F7EEF9',
    customizable: true,
  },
];
